import type { ChangeAlert, Dataset, Metric, Project, Proposal, Version, WorkspaceData } from './types'

// Explicitly isolated local snapshot. It is never used by the real FastAPI client.
const project: Project = { id: 'demo-greenfield', name: 'Greenfield ward · synthetic study area', location: 'Nashik district · Maharashtra', updatedAt: '2026-09-30T14:42:00Z', status: 'needs-attention', datasetCount: 4, pendingReview: 12 }
const square = (x: number, y: number, id: string, status: string): GeoJSON.Feature => ({ type: 'Feature', properties: { id, status, label: `Plot ${id}` }, geometry: { type: 'Polygon', coordinates: [[[x, y], [x + .008, y], [x + .008, y + .007], [x, y + .007], [x, y]]] } })
const features = [square(73.782, 19.997, '45', 'accepted'), square(73.791, 19.997, '46', 'pending'), square(73.800, 19.997, '47', 'conflict'), square(73.782, 20.005, '48', 'accepted'), square(73.791, 20.005, '49', 'pending'), square(73.800, 20.005, '50', 'accepted'), square(73.782, 20.013, '51', 'conflict'), square(73.791, 20.013, '52', 'accepted'), square(73.800, 20.013, '53', 'pending')]
const polygon = (index: number) => features[index % features.length].geometry as GeoJSON.Polygon

const datasets: Dataset[] = [
  { id: 'ds-cad', name: 'greenfield_cadastral_2024.geojson', source: 'District Land Records', kind: 'Cadastral polygons', format: 'GeoJSON', records: 1000, crs: 'EPSG:32643', crsStatus: 'verified', captureDate: '2024-03-18', uploadedAt: '2026-09-30T09:12:00Z', status: 'ready', issues: [] },
  { id: 'ds-muni', name: 'ward_07_municipal.geojson', source: 'Municipal GIS cell', kind: 'Municipal polygons', format: 'GeoJSON', records: 987, crs: 'EPSG:32643', crsStatus: 'verified', captureDate: '2025-01-14', uploadedAt: '2026-09-30T09:16:00Z', status: 'ready', issues: ['13 features have > 0.5m boundary delta'] },
  { id: 'ds-revenue', name: 'revenue_register_aliases.csv', source: 'Revenue department', kind: 'Revenue table', format: 'CSV', records: 1018, crs: 'Not applicable', crsStatus: 'verified', captureDate: '2025-12-06', uploadedAt: '2026-09-30T09:20:00Z', status: 'needs-review', issues: ['8 duplicate Khasra numbers', '14 missing area values'] },
  { id: 'ds-survey', name: 'survey_checkpoints.zip', source: 'Field survey team', kind: 'Survey checkpoints', format: 'SHP ZIP', records: 84, crs: 'Unknown', crsStatus: 'missing', captureDate: '2026-02-21', uploadedAt: '2026-09-30T09:24:00Z', status: 'needs-review', issues: ['CRS metadata is missing; matching is paused'] },
]
const proposal = (id: string, index: number, score: number, subtitle: string, boundaryConflict: boolean, status: Proposal['status'], overlap: string, distance: string, area: string, conflicts: string[] = []): Proposal => ({ id: `prop-${id}`, parcelId: `Parcel entity ${id}`, sourceIds: [`CAD-${id}`, `MUN-${id}`, `K-${id}`], title: `Plot ${id} ↔ Parcel_${id}`, subtitle, score, scoreLabel: score > .9 ? 'Strong evidence' : score > .7 ? 'Uncalibrated ranking' : 'Ambiguous ranking', status, boundaryConflict, geometry: polygon(index), evidence: [{ label: 'Identifier agreement', value: score > .7 ? 'Exact' : 'Partial', tone: score > .7 ? 'good' : 'warn' }, { label: 'Polygon overlap', value: overlap, tone: score > .85 ? 'good' : 'warn' }, { label: 'Centroid distance', value: distance, tone: score > .85 ? 'good' : 'warn' }, { label: 'Area difference', value: area, tone: score > .85 ? 'neutral' : 'warn' }], reasons: ['Identifiers agree within the Greenfield ward namespace', 'Overlap and centroid distance were compared against configured source accuracy', boundaryConflict ? 'Boundary delta affects neighboring parcels and needs officer approval' : 'No neighboring assignment conflict'], alternatives: [{ id: `MUN-${Number(id) + 1}`, label: `Parcel_${Number(id) + 1}`, score: Math.max(.18, score - .22), note: 'Adjacent; identifier mismatch' }, { id: `MUN-${Number(id) - 1}`, label: `Parcel_${Number(id) - 1}`, score: Math.max(.12, score - .37), note: 'Spatial alternative' }], conflicts, sourceValues: [{ source: 'Cadastral', identifier: `Plot ${id}`, area: area === '3.1%' ? '1,248.6 m²' : '2,104.0 m²', updated: '18 Mar 2024' }, { source: 'Municipal', identifier: `Parcel_${id}`, area: area === '3.1%' ? '1,209.8 m²' : '2,579.8 m²', updated: '14 Jan 2025' }, { source: 'Revenue', identifier: `Khasra ${id}`, area: conflicts.length ? '—' : '1,230.0 m²', updated: '06 Dec 2025' }] })
const proposals: Proposal[] = [proposal('45', 0, .94, 'Routine identity match', false, 'accepted', '92.4%', '1.8 m', '3.1%'), proposal('46', 1, .78, 'Review recommended', false, 'pending', '78.1%', '7.4 m', '11.9%', ['Revenue area is missing from the latest register']), proposal('47', 2, .81, 'Boundary approval required', true, 'pending', '81.0%', '3.2 m', '22.6%', ['Boundary movement affects 2 neighboring parcels', 'Cadastral and municipal areas disagree by 22.6%']), proposal('51', 6, .63, 'Needs field verification', true, 'deferred', '65.0%', '12.6 m', '28.4%', ['Missing CRS blocks survey evidence', 'Possible split/merge pattern'])]
const alerts: ChangeAlert[] = [{ id: 'a47', parcelId: 'Parcel 47', type: 'Geometry change', severity: 'high', summary: 'Boundary moved 3.2 m toward access lane', before: '1,248.3 m² · v2024.03', after: '1,502.7 m² · v2025.01', detectedAt: '30 Sep 2026, 09:34', status: 'unreviewed' }, { id: 'a88', parcelId: 'Parcel 88', type: 'Attribute change', severity: 'medium', summary: 'Khasra suffix changed from 88 to 88-B', before: 'Khasra 88', after: 'Khasra 88-B', detectedAt: '30 Sep 2026, 09:36', status: 'unreviewed' }, { id: 'a102', parcelId: 'Parcel 102', type: 'Missing from snapshot', severity: 'medium', summary: 'Feature is absent from the 2025 municipal snapshot', before: 'Present · v2024.03', after: 'Not found · v2025.01', detectedAt: '30 Sep 2026, 09:39', status: 'unreviewed' }, { id: 'a19', parcelId: 'Parcel 19', type: 'New feature', severity: 'low', summary: 'New polygon appears in the 2025 municipal snapshot', before: 'Not found · v2024.03', after: 'Present · v2025.01', detectedAt: '30 Sep 2026, 09:42', status: 'reviewed' }]
const versions: Version[] = [{ id: 'v-2026-09-30', label: 'Review batch · 30 Sep 2026', status: 'In review', createdAt: '30 Sep 2026, 09:44', createdBy: 'Aarav Mehta', records: 986, changeSummary: '12 proposals pending · 3 conflicts' }, { id: 'v-2025-01-14', label: 'Published · 14 Jan 2025', status: 'Published', createdAt: '14 Jan 2025, 16:20', createdBy: 'Priya Nair', records: 975, changeSummary: 'Municipal alignment baseline' }, { id: 'v-2024-03-18', label: 'Published · 18 Mar 2024', status: 'Published', createdAt: '18 Mar 2024, 11:08', createdBy: 'Rohan Deshmukh', records: 1000, changeSummary: 'Cadastral source registration' }]
const metrics: Metric[] = [{ label: 'Source records', value: '3,089', delta: '+4.8%', context: 'across 4 registered datasets', icon: 'layers', tone: 'green' }, { label: 'Review queue', value: '12', delta: '4 high attention', context: 'proposals need an officer', icon: 'review', tone: 'amber' }, { label: 'Open conflicts', value: '3', delta: '2 boundary changes', context: 'must be resolved before publish', icon: 'warning', tone: 'rose' }, { label: 'Last processing', value: '01:42', delta: 'completed', context: 'baseline · 30 Sep 2026', icon: 'clock', tone: 'blue' }]

const initial: WorkspaceData = { projects: [project], datasets, proposals, alerts, versions, metrics, geojson: { type: 'FeatureCollection', features }, activity: [{ id: 'a1', type: 'process', title: 'Baseline matching completed', detail: '1,000 candidates · 12 routed to review', time: '18 min ago' }, { id: 'a2', type: 'upload', title: 'Revenue register uploaded', detail: 'revenue_register_aliases.csv · 1,018 rows', time: '2 hr ago' }, { id: 'a3', type: 'review', title: '4 routine matches accepted', detail: 'by Aarav Mehta · Review batch', time: 'Yesterday' }, { id: 'a4', type: 'publish', title: 'Version v2025.01 published', detail: '975 reviewed parcel entities', time: '14 Jan 2025' }] }
let current = structuredClone(initial)
export function demoLogin() { return { token: 'demo-local-token', user: { name: 'Aarav Mehta', role: 'Senior GIS Officer' } } }
export function demoWorkspace(): WorkspaceData { return structuredClone(current) }
export function demoBootProject(): Project { return project }
export function demoUpload(file: File): Dataset { const csv = file.name.toLowerCase().endsWith('.csv'); const item: Dataset = { id: `upload-${Date.now()}`, name: file.name, source: 'Officer upload', kind: csv ? 'Revenue table' : 'Cadastral polygons', format: csv ? 'CSV' : 'GeoJSON', records: 0, crs: csv ? 'Not applicable' : 'Unknown', crsStatus: csv ? 'verified' : 'missing', uploadedAt: new Date().toISOString(), status: csv ? 'ready' : 'needs-review', issues: csv ? ['Record count will be available after processing'] : ['CRS metadata needs confirmation'] }; current.datasets = [item, ...current.datasets]; return structuredClone(item) }
export function demoReview(id: string, action: 'accept' | 'reject' | 'defer', note: string): Proposal { const item = current.proposals.find((p) => p.id === id); if (!item) throw new Error('Proposal not found'); if (action === 'accept' && item.boundaryConflict) throw new Error('Boundary approval is required before this proposal can be accepted.'); item.status = action === 'accept' ? 'accepted' : action === 'reject' ? 'rejected' : 'deferred'; item.reviewNote = note; return structuredClone(item) }
export function demoProcess() { current.activity.unshift({ id: `p-${Date.now()}`, type: 'process', title: 'Baseline matching completed', detail: 'Synthetic run · proposal scores refreshed', time: 'Just now' }) }
export function demoValidate() { return { status: 'attention', checks: [{ label: 'Geometry validity', status: 'pass', detail: '986 of 986 reviewed geometries valid' }, { label: 'CRS readiness', status: 'attention', detail: 'Survey checkpoints still lack CRS metadata' }, { label: 'Boundary approvals', status: 'blocked', detail: '2 proposals require explicit approval' }, { label: 'Lineage completeness', status: 'pass', detail: '100% of current published features traceable' }] } }
export function demoPublish(): Version { const item = structuredClone(current.versions[0]); item.status = 'Published'; item.label = 'Published · just now'; current.versions[0] = item; return item }
