import { useState } from 'react'
import * as w from './workflowApi'
type Result={ plan:Record<string,unknown>; rows:Record<string,unknown>[]; total?:number; clarification?:string; read_only:boolean }
export default function QueryPanel({project,fieldOnly=false,run}:{project:string;fieldOnly?:boolean;run:(action:()=>Promise<void>)=>void}) {
  const [query,setQuery]=useState(fieldOnly?'nearby tasks':'show conflicts in ward W-1'); const [result,setResult]=useState<Result>()
  const [ward,setWard]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [bbox,setBbox]=useState(''); const [longitude,setLongitude]=useState(''); const [latitude,setLatitude]=useState(''); const [radius,setRadius]=useState(''); const [limit,setLimit]=useState('25'); const [offset,setOffset]=useState(0)
  const execute=(page:number)=>run(async()=>{ const body={query,ward:ward || undefined,date_from:from || undefined,date_to:to || undefined,bbox:bbox?bbox.split(',').map(Number):undefined,longitude:longitude?Number(longitude):undefined,latitude:latitude?Number(latitude):undefined,radius_m:radius?Number(radius):undefined,limit:Number(limit),offset:page};setResult(await w.post<Result>(`${w.projectPath(project)}/query`,body));setOffset(page) })
  const columns=[...new Set(result?.rows.flatMap(row=>Object.keys(row)) || [])]
  return <section className="panel inspector"><h2>Read-only spatial query</h2><p>Deterministic Hindi/English parser. Results respect account/project roles and source classification. Filters run before pagination; queries cannot mutate records.{fieldOnly?' This account can query its nearby active assignments only.':''}</p><form onSubmit={e=>{e.preventDefault();execute(0)}}><label>Query<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="conflicts / missing links / area above 100 / nearby tasks" /></label><details open={fieldOnly}><summary>Exact filters and location</summary><div className="mapping-grid"><label>Exact ward<input value={ward} onChange={e=>setWard(e.target.value)} /></label><label>Query date from<input type="date" value={from} onChange={e=>setFrom(e.target.value)} /></label><label>Query date to<input type="date" value={to} onChange={e=>setTo(e.target.value)} /></label><label>CRS84 bounding box<input value={bbox} placeholder="min longitude,min latitude,max longitude,max latitude" onChange={e=>setBbox(e.target.value)} /></label><label>Query longitude<input type="number" min="-180" max="180" step="any" value={longitude} onChange={e=>setLongitude(e.target.value)} /></label><label>Query latitude<input type="number" min="-90" max="90" step="any" value={latitude} onChange={e=>setLatitude(e.target.value)} /></label><label>Radius in metres<input type="number" min="1" max="10000" value={radius} onChange={e=>setRadius(e.target.value)} /></label><label>Rows per page<select value={limit} onChange={e=>setLimit(e.target.value)}>{['25','50','100'].map(n=><option key={n}>{n}</option>)}</select></label></div><button type="button" className="button button-secondary" onClick={()=>navigator.geolocation?.getCurrentPosition(p=>{setLongitude(String(p.coords.longitude));setLatitude(String(p.coords.latitude));setRadius('1000')})}>Use current location</button></details><button className="button button-primary">Run bounded query</button></form>
    {result && <><details open><summary>Interpreted plan</summary><pre className="json-preview">{JSON.stringify(result.plan,null,2)}</pre></details>{result.clarification && <p role="status">{result.clarification}</p>}<p>{result.total ?? result.rows.length} authorized results · showing {result.rows.length} from offset {offset}</p>{result.rows.length>0 && <div className="comparison-table"><table><thead><tr>{columns.map(key=><th key={key}>{key.replace(/_/g,' ')}</th>)}</tr></thead><tbody>{result.rows.map((row,i)=><tr key={i}>{columns.map(key=><td key={key}>{typeof row[key]==='object'?JSON.stringify(row[key]):String(row[key]??'')}</td>)}</tr>)}</tbody></table></div>}<button className="button button-secondary" disabled={!offset} onClick={()=>execute(Math.max(0,offset-Number(limit)))}>Previous results</button><button className="button button-secondary" disabled={offset+result.rows.length>=(result.total ?? result.rows.length)} onClick={()=>execute(offset+Number(limit))}>Next results</button></>}
  </section>
}
