import { useCallback, useEffect, useState } from 'react'
import * as w from './workflowApi'
const canonicalFields=['parcel_id','survey_number','property_account','village','village_code','district','ward','recorded_area','area_units']
type Case={ id:string; source_feature_ids:string[]; status:string; revision:number; recommendation:Record<string,unknown>; competing_values:Record<string,unknown>; evidence:unknown[]; rationale?:string }
function CaseReview({ item, features, canReview, decide }: { item:Case; features:w.Feature[]; canReview:boolean; decide:(body:unknown)=>void }) {
  const members=features.filter(f=>item.source_feature_ids.includes(f.id))
  const [geometry,setGeometry]=useState(''); const [attribute,setAttribute]=useState(''); const [fields,setFields]=useState<Record<string,string>>({}); const [reason,setReason]=useState(''); const [selection,setSelection]=useState(false)
  const allFields=[...new Set(members.flatMap(f=>Object.keys(f.canonical_attributes || f.attributes)))].sort()
  const choice=(f:w.Feature)=>`${f.dataset_name || f.dataset_id} · ${f.original_id || f.id}`
  const action=(decision:string)=>decide({decision,expected_revision:item.revision,rationale:reason,approve_selection:decision==='accepted' && selection,geometry_source_id:geometry || null,attribute_source_id:attribute || null,attribute_sources:fields})
  return <details open={['proposed','pending','draft','deferred'].includes(item.status)}><summary>Case {item.id.slice(0,8)} · {item.status} · revision {item.revision}</summary>
    <div className="comparison-table"><table><thead><tr><th>Field</th>{members.map(f=><th key={f.id}>{choice(f)}</th>)}<th>Explicit field source</th></tr></thead><tbody>{allFields.map(field=><tr key={field}><th>{field}</th>{members.map(f=><td key={f.id}>{JSON.stringify((f.canonical_attributes || f.attributes)[field]) || 'Not supplied'}</td>)}<td><select aria-label={`Case ${item.id} field ${field}`} value={fields[field] || ''} disabled={!canReview || !selection} onChange={e=>setFields(current=>{const next={...current}; if(e.target.value) next[field]=e.target.value; else delete next[field]; return next})}><option value="">Use default attribute source</option>{members.filter(f=>field in (f.canonical_attributes || f.attributes)).map(f=><option key={f.id} value={f.id}>{choice(f)}</option>)}</select></td></tr>)}</tbody></table></div>
    <details><summary>Agreement, competing values and spatial evidence</summary><pre className="json-preview">{JSON.stringify({agreement:item.recommendation,competing:item.competing_values,evidence:item.evidence},null,2)}</pre></details>
    {['proposed','pending','draft','deferred'].includes(item.status) && <><label><input type="checkbox" checked={selection} onChange={e=>setSelection(e.target.checked)} disabled={!canReview} /> Explicitly approve a publication baseline with this identity decision</label>{selection && <><label>Reconciliation boundary source<select value={geometry} onChange={e=>setGeometry(e.target.value)}><option value="">No spatial boundary (attribute-only record)</option>{members.filter(f=>f.geometry).map(f=><option key={f.id} value={f.id}>{choice(f)}</option>)}</select></label><label>Reconciliation default attribute source<select value={attribute} onChange={e=>setAttribute(e.target.value)}><option value="">Choose evidenced source</option>{members.map(f=><option key={f.id} value={f.id}>{choice(f)}</option>)}</select></label></>}
    <label>Reconciliation rationale<input value={reason} onChange={e=>setReason(e.target.value)} /></label><div className="title-actions">{['accepted','deferred','rejected'].map(decision=><button key={decision} className="button button-secondary" disabled={!canReview || !reason.trim() || (decision==='accepted' && selection && !attribute)} onClick={()=>action(decision)}>{decision==='accepted'?'Accept reconciliation':decision==='rejected'?'Reject reconciliation':'Defer reconciliation'}</button>)}</div></>}
    {Boolean(item.recommendation.canonical_parcel_id) && <p>Canonical parcel: {String(item.recommendation.canonical_parcel_id)} · explicit baseline: {String(item.recommendation.selection_explicitly_approved)}</p>}
  </details>
}
export default function RegistryTools({project,features,matches,writable,canReview,refreshProject,run}:{project:string;features:w.Feature[];matches:w.Evidence[];writable:boolean;canReview:boolean;refreshProject:()=>Promise<void>;run:(action:()=>Promise<void>)=>void}) {
  const [chosen,setChosen]=useState<string[]>([]); const [cases,setCases]=useState<Case[]>([]); const [dictionary,setDictionary]=useState<Record<string,unknown>[]>([]); const [rankers,setRankers]=useState<w.ModelArtifact[]>([])
  const [term,setTerm]=useState(''); const [canonical,setCanonical]=useState('parcel_id'); const [rationale,setRationale]=useState(''); const [comparisonReason,setComparisonReason]=useState('')
  const [proposal,setProposal]=useState(''); const [label,setLabel]=useState('1'); const [group,setGroup]=useState(''); const [split,setSplit]=useState('train'); const [version,setVersion]=useState(''); const [seed,setSeed]=useState('42'); const [trainingMessage,setTrainingMessage]=useState('')
  const refresh=useCallback(async()=>{const [c,d,r]=await Promise.all([w.get<Case[]>(`${w.projectPath(project)}/reconciliations`),w.get<Record<string,unknown>[]>(`${w.projectPath(project)}/mapping-dictionary`),w.get<w.ModelArtifact[]>(`${w.projectPath(project)}/ranker`)]);setCases(c);setDictionary(d);setRankers(r)},[project])
  useEffect(()=>{run(refresh)},[refresh,run])
  return <section className="panel inspector"><h2>Source harmonization tools</h2><p>Select records from at least three distinct datasets. Review agreement and competing values, then choose boundary and per-field evidence explicitly. Accepting identity alone does not approve a publication baseline.</p>
    <div className="record-preview">{features.filter(f=>f.status==='processed').map(f=><label key={f.id}><input type="checkbox" checked={chosen.includes(f.id)} onChange={()=>setChosen(current=>current.includes(f.id)?current.filter(id=>id!==f.id):[...current,f.id].slice(-20))} /> {f.original_id || f.id} · {f.dataset_name}</label>)}</div>
    <label>Comparison rationale<input value={comparisonReason} onChange={e=>setComparisonReason(e.target.value)} /></label><button className="button button-secondary" disabled={!writable || chosen.length<3 || !comparisonReason.trim()} onClick={()=>run(async()=>{await w.post(`${w.projectPath(project)}/reconciliations`,{source_feature_ids:chosen,rationale:comparisonReason});setChosen([]);await refresh()})}>Compare {chosen.length} independent sources</button>
    <h3>Reconciliation cases ({cases.length})</h3>{cases.map(item=><CaseReview key={`${item.id}-${item.revision}`} item={item} features={features} canReview={canReview} decide={body=>run(async()=>{try{await w.post(`${w.projectPath(project)}/reconciliations/${item.id}/decision`,body)}finally{await refresh();await refreshProject()}})} />)}
    <details><summary>Hindi / English reviewed dictionary</summary><form onSubmit={e=>{e.preventDefault();run(async()=>{await w.post(`${w.projectPath(project)}/mapping-dictionary`,{canonical_field:canonical,source_term:term,language:/[\u0900-\u097F]/.test(term)?'hi':'en',normalized_term:term,rationale,confirm:canReview});setTerm('');setRationale('');await refresh()})}}><label>Canonical field<select value={canonical} onChange={e=>setCanonical(e.target.value)}>{canonicalFields.map(field=><option key={field}>{field}</option>)}</select></label><label>Source term<input required value={term} onChange={e=>setTerm(e.target.value)} placeholder="खसरा संख्या / Khasra No" /></label><label>Dictionary rationale<input required value={rationale} onChange={e=>setRationale(e.target.value)} /></label><button className="button button-secondary" disabled={!writable}>Save reviewed term</button></form><pre className="json-preview">{JSON.stringify(dictionary,null,2)}</pre></details>
    <details><summary>Reviewed training labels and model ranking</summary><p>Labels must follow evidence review. Related parcels/sources must share a group and stay in one split. The optional logistic ranker reports held-out metrics; its output remains an uncalibrated ranking score.</p><label>Training proposal<select value={proposal} onChange={e=>setProposal(e.target.value)}><option value="">Choose reviewed proposal</option>{matches.filter(m=>['accepted','rejected'].includes(m.status)).map(m=><option key={m.id} value={m.id}>{m.id.slice(0,8)} · {m.status}</option>)}</select></label><label>Reviewed training label<select value={label} onChange={e=>setLabel(e.target.value)}><option value="1">Match</option><option value="0">Non-match / hard negative</option></select></label><label>Related parcel/source group<input value={group} onChange={e=>setGroup(e.target.value)} /></label><label>Training split<select value={split} onChange={e=>setSplit(e.target.value)}>{['train','calibration','validation','test'].map(value=><option key={value}>{value}</option>)}</select></label><button className="button button-secondary" disabled={!canReview || !proposal || !group.trim()} onClick={()=>run(async()=>{const saved=await w.post<Record<string,unknown>>(`${w.projectPath(project)}/training-examples`,{proposal_id:proposal,label:Number(label),group_key:group,split,hard_negative:label==='0'});setTrainingMessage(`Saved reviewed label ${String(saved.id)}`)})}>Save reviewed label</button>
    <label>Model version<input value={version} onChange={e=>setVersion(e.target.value)} /></label><label>Training seed<input type="number" value={seed} onChange={e=>setSeed(e.target.value)} /></label><button className="button button-secondary" disabled={!canReview || !version.trim()} onClick={()=>run(async()=>{await w.post(`${w.projectPath(project)}/ranker/train`,{seed:Number(seed),version});await refresh();setTrainingMessage('Trained on grouped labels. Review held-out validation before activating.')})}>Train optional ranker</button>{trainingMessage && <p role="status">{trainingMessage}</p>}
    {rankers.map(rank=><details key={rank.id}><summary>{rank.version} · {rank.activation_status || 'inactive'}</summary><pre className="json-preview">{JSON.stringify(rank.metrics,null,2)}</pre><button className="button button-secondary" disabled={!canReview} onClick={()=>run(async()=>{await w.post(`${w.projectPath(project)}/ranker/${rank.id}/activation`,{active:rank.activation_status!=='active'});await refresh()})}>{rank.activation_status==='active'?'Deactivate':'Activate for ranking'}</button></details>)}</details>
  </section>
}
